version: '3'
services:
  web1:
    image: 'nginx:latest'
    ports:
      - '8080:80'
    volumes:
      - './web1/html:/usr/share/nginx/html'
  web2:
    image: 'nginx:latest'
    ports:
      - '8081:80'
    volumes:
      - './web2/html:/usr/share/nginx/html'
  haproxy:
    image: eeacms/haproxy
    ports:
      - '8082:8082'
      - '1936:1936'
    volumes:
      - './haproxy:/usr/local/etc/haproxy/'
